apiVersion: v2
name: JamApp-backend # This value was modified by the initial-setup python script
description: A Helm chart for deploying JamApp-backend # This value was modified by the initial-setup python script
version: 1.0